name: GitHub Actions Demo
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:

jobs:
  job01:
    runs-on: ubuntu-latest
    environment: Test

    steps:
    - run: echo 'Testing'

  job02:    
    needs: job01
    runs-on: ubuntu-latest
    environment: Load-Test
    
    steps:
    - run: echo 'Testing'

  job03:  
    needs: job02
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
    - run: echo 'Production'

    
  hellojob:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./

  job1:
    name: Testes
    runs-on: utubuntu-latest

    steps:
    - run: echo '${{toJSON(github)}}'
    
    
    
  
