name: GitHub Actions Demo
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:

jobs:
  hellojob:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: action        

  job1:
    name: Testes
    runs-on: utubuntu-latest

    steps:
    - run: echo '${{toJSON(github)}}'
    
    
    
  
