name: GitHub Actions Demo
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: "0 6 15 * 7"
  workflow_dispatch:

jobs:
  job1:
    name: Testes
    runs-on: utubuntu-latest

    steps:
    - run: echo '${{toJSON(github)}}'
    
    
    
  
